name: garden_flutter
description: BLE test app for garden monitoring

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Pinned safe version
  permission_handler: 12.0.1

  # Flutter core dependencies (these are automatically managed):
  cupertino_icons: ^1.0.8
  flutter_reactive_ble: ^5.4.0
  characters: 1.4.0
  collection: 1.19.1
  fixnum: 1.1.1
  functional_data: 1.2.0
  material_color_utilities: 0.11.1
  meta: 1.16.0
  protobuf: 2.1.0
  vector_math: 2.1.4
